import Head from 'next/head';
import { useEffect, useState } from 'react';
import Contact from '../components/Contact';
import Hero from '../components/Hero';
import { Projects } from '../components/Projects';
import { Services } from '../components/Services';
import Pie from '../components/Pie';



export default function Home() {  
  return (
    <div className='{styles.container}'>
      <Head>
        <title>C7 Studio</title>
        <meta name='description' content='generated by create-ivan-app' />
        <link rel='icon' href='/favicon3.png' />
      </Head>
      <Hero/>
      <Services/>
      <Projects/>
      <Contact/>
      <Pie/>
    </div>
  )
}